apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: gitlist-pipeline
spec:
  params:
    - name: repo_url
      type: string
      description: Git repository URL
  workspaces:
    - name: source
      description: Shared workspace for tasks
  tasks:
    - name: clone
      taskRef:
        name: git-clone-local
      params:
        - name: repo_url
          value: $(params.repo_url)
      workspaces:
        - name: source
          workspace: source

    - name: list
      runAfter:
        - clone
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: ls
            image: registry.access.redhat.com/ubi9/ubi:latest
            script: |
              echo "Files in repo:"
              ls -la $(workspaces.source.path)
      workspaces:
        - name: source
          workspace: source

